PREFIX dbo: <http://dbpedia.org/ontology/>
PREFIX category: <http://dbpedia.org/resource/Category:>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX wd: <http://www.wikidata.org/entity/>

SELECT ?disease ?dn ?wikiPage ?icd9 ?icd10 ?disDB ?meshID ?mlp ?omim ?emed ?frbase ?wikidata_id
WHERE {
    ?disease a dbo:Disease .
    ?disease foaf:isPrimaryTopicOf ?wikiPage .
OPTIONAL { ?disease <http://dbpedia.org/ontology/icd9> ?icd9. }
	OPTIONAL { ?disease <http://dbpedia.org/ontology/icd10> ?icd10. }
	OPTIONAL { ?disease <http://dbpedia.org/ontology/diseasesDb> ?disDB. }
	OPTIONAL { ?disease <http://dbpedia.org/ontology/meshId> ?meshID. }
	OPTIONAL { ?disease <http://dbpedia.org/property/medlineplus> ?mlp. }
	OPTIONAL { ?disease <http://dbpedia.org/ontology/omim> ?omim. }
	OPTIONAL { ?disease <http://dbpedia.org/property/emedicinetopic> ?emed. }
	OPTIONAL { VALUES (?wikidata_id) {(owl:sameAs)}   . }
	OPTIONAL {
  		?disease owl:sameAs ?frbase.
  		FILTER(regex(str(?frbase), "freebase", "i")).
	}
        OPTIONAL {
                ?disease rdfs:label ?dn.
                FILTER (lang(?dn) = 'en')
        }
}

ORDER BY ?disease